name: Run unit tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - python-version: '3.7'
            numpy-version: '1.15'
            setuptools-version: '40.0'
            pip-version: '18.0'
            wheel-version: '0.32'
            pyyaml-version: '3.13'
          - python-version: '3.8'
            numpy-version: '1.18'
            setuptools-version: '41.5'
            pip-version: '19.3'
            wheel-version: '0.34'
            pyyaml-version: '5.2'
          - python-version: '3.9'
            numpy-version: '1.20'
            setuptools-version: '51.0'
            pip-version: '20.3'
            wheel-version: '0.36'
            pyyaml-version: '5.4'
          - python-version: '3.10'
            numpy-version: '1.22'
            setuptools-version: '58.3'
            pip-version: '21.3'
            wheel-version: '0.38'
            pyyaml-version: '6.0'
          - python-version: '3.11'
            numpy-version: '1.24'
            setuptools-version: '65.6'
            pip-version: '23.0'
            wheel-version: '0.40'
            pyyaml-version: '6.0'
        #   - python-version: '3.12'
        #     numpy-version: 1.26
        #     setuptools-version: 69.0
        #     pip-version: '23.3'
        #     wheel-version: 0.42
        #     pyyaml-version: '6.0'
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install pip==${{ matrix.pip-version }}
        pip install wheel==${{ matrix.wheel-version }}
        pip install setuptools==${{ matrix.setuptools-version }}
        pip install numpy==${{ matrix.numpy-version }}
        pip install pyyaml==${{ matrix.pyyaml-version }}
        pip install -r requirements.txt
        
    - name: Run unit tests
      run: |
        python -m unittest discover deepmd_iterative/unittests
