name: Run unit tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - python-version: "3.7"
            numpy-version: "1.17"
          - python-version: "3.7"
            numpy-version: "1.18"
            setuptools-version: "40"
          - python-version: "3.8"
            numpy-version: "1.19"
            setuptools-version: "43"
          - python-version: "3.8"
            numpy-version: "1.20"
            setuptools-version: "43"
          - python-version: "3.9"
            numpy-version: "1.21"
            setuptools-version: "51"
          - python-version: "3.9"
            numpy-version: "1.22"
            setuptools-version: "60"
          - python-version: "3.10"
            numpy-version: "1.23"
            setuptools-version: "60"
          - python-version: "3.10"
            numpy-version: "1.24"
          - python-version: "3.11"
            numpy-version: "1.25"
          - python-version: "3.12"
            numpy-version: "1.26"
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install numpy==${{ matrix.numpy-version }}
        pip install setuptools==${{ matrix.setuptools-version }}
        pip install -r requirements.txt
        
    - name: Run unit tests
      run: |
        python -m unittest discover deepmd_iterative/unittests
